# Generated by Django 4.2.4 on 2023-08-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buggy',
            fields=[
                ('idBuggy', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('haki', models.CharField(choices=[('armadura', 'Haki de armadura'), ('observacion', 'Haki de observacion'), ('rey', 'Haki del rey')], max_length=25)),
                ('edad', models.IntegerField()),
                ('dia', models.CharField(max_length=15)),
                ('hora', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Luffy',
            fields=[
                ('idLuffy', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('haki', models.CharField(choices=[('armadura', 'Haki de armadura'), ('observacion', 'Haki de observacion'), ('rey', 'Haki del rey')], max_length=25)),
                ('edad', models.IntegerField()),
                ('dia', models.CharField(max_length=15)),
                ('hora', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Shanks',
            fields=[
                ('idShanks', models.IntegerField(primary_key=True, serialize=False)),
                ('haki', models.CharField(choices=[('armadura', 'Haki de armadura'), ('observacion', 'Haki de observacion'), ('rey', 'Haki del rey')], max_length=25)),
                ('nombre', models.CharField(max_length=25)),
                ('edad', models.IntegerField()),
                ('dia', models.CharField(max_length=15)),
                ('hora', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Teach',
            fields=[
                ('idTeach', models.IntegerField(primary_key=True, serialize=False)),
                ('haki', models.CharField(choices=[('armadura', 'Haki de armadura'), ('observacion', 'Haki de observacion'), ('rey', 'Haki del rey')], max_length=25)),
                ('nombre', models.CharField(max_length=25)),
                ('edad', models.IntegerField()),
                ('dia', models.CharField(max_length=15)),
                ('hora', models.CharField(max_length=10)),
            ],
        ),
    ]
